# Generated by Django 5.2.4 on 2025-10-27 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("market", "0002_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inflationprice",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="market.item"
            ),
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
