# Generated by Django 5.2.4 on 2025-10-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_inflationprice_item_delete_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionsetting",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
