# Generated by Django 5.2.4 on 2025-11-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_competitionsetting_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="inflationprice",
            name="applied_round",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
