# Generated by Django 5.2.4 on 2025-11-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_inflationprice_applied_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inflationprice",
            name="applied_round",
        ),
        migrations.AddField(
            model_name="competitionsetting",
            name="applied_round",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="competitionsetting",
            name="total_inflation_rounds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inflationprice",
            name="round_number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
