# Generated by Django 5.0.7 on 2025-10-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("easy", "آسان"),
                            ("medium", "متوسط"),
                            ("hard", "سخت"),
                        ],
                        max_length=10,
                        verbose_name="سطح سوال",
                    ),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت فروش"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد در بانک"
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوال\u200cها",
                "ordering": ["level"],
            },
        ),
    ]
