# Generated by Django 5.0.7 on 2025-10-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sell_price",
            field=models.DecimalField(
                decimal_places=0, default=1, max_digits=10, verbose_name="قیمت فروش"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="buy_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="قیمت فروش"
            ),
        ),
    ]
