# Generated by Django 5.2.4 on 2025-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_question_sell_price_alter_question_buy_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="buy_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="قیمت خرید"
            ),
        ),
    ]
