# Generated by Django 5.0.7 on 2025-10-17 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کالا")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت پایه"
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت فعلی"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.item"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "کالای تیم",
                "verbose_name_plural": "کالاهای تیم",
                "unique_together": {("team", "item")},
            },
        ),
    ]
