# Generated by Django 5.2.4 on 2025-10-27 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "کالا", "verbose_name_plural": "کالاها"},
        ),
    ]
