# Generated by Django 5.0.7 on 2025-10-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=100, verbose_name="نام گروه"),
                ),
                ("members", models.TextField(verbose_name="اعضای گروه")),
                (
                    "team_number",
                    models.PositiveIntegerField(unique=True, verbose_name="شماره گروه"),
                ),
                (
                    "cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=700,
                        max_digits=12,
                        verbose_name="پول نقد",
                    ),
                ),
                (
                    "bank_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="موجودی حساب بانکی",
                    ),
                ),
                (
                    "unsolved_questions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد سوال\u200cهای حل\u200cنشده"
                    ),
                ),
                (
                    "solved_questions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد سوال\u200cهای حل\u200cشده"
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=700,
                        max_digits=14,
                        verbose_name="کل دارایی",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(default=1, verbose_name="رتبه دارایی"),
                ),
            ],
            options={
                "verbose_name": "گروه",
                "verbose_name_plural": "گروه\u200cها",
                "ordering": ["team_number"],
            },
        ),
    ]
