# Generated by Django 5.0.7 on 2025-10-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="items",
            field=models.ManyToManyField(
                related_name="teams",
                through="market.TeamItem",
                to="market.item",
                verbose_name="کالاهای خریداری\u200cشده",
            ),
        ),
    ]
