# Generated by Django 5.0.7 on 2025-10-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="bank_balance",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="موجودی حساب بانکی",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="cash",
            field=models.DecimalField(
                decimal_places=0, default=700, max_digits=12, verbose_name="پول نقد"
            ),
        ),
    ]
