# Generated by Django 5.2.4 on 2025-10-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_team_bank_balance_alter_team_cash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="cash",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="پول نقد"
            ),
        ),
    ]
