# Generated by Django 5.2.4 on 2025-10-30 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_team_cash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="cash",
        ),
    ]
