# Generated by Django 5.2.4 on 2025-11-04 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_team_cash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="rank",
        ),
    ]
